name: Bug Report
description: Report a bug or unexpected behavior in tunacode
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: If applicable, paste any error messages or logs
      render: shell

  - type: input
    id: version
    attributes:
      label: Tunacode Version
      description: Run `tunacode --version` or check pyproject.toml
      placeholder: "0.1.43"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Run `python3 --version`
      placeholder: "3.12.3"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "Ubuntu 22.04, macOS 14.0, Windows 11"
    validations:
      required: true

  - type: dropdown
    id: terminal
    attributes:
      label: Terminal Emulator
      description: Which terminal are you using?
      options:
        - iTerm2
        - Terminal.app
        - Alacritty
        - Kitty
        - Windows Terminal
        - WSL2
        - tmux
        - Other (specify in additional context)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
