name: Question or Help
description: Ask a question or get help with tunacode
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide details about what you need assistance with.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "How do I..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about what you're trying to accomplish
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: If applicable, what have you already attempted?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      options:
        - label: I have checked the documentation
          required: false
        - label: I have searched existing issues
          required: false
